#!/usr/bin/env python3
"""Run this skill's unittest modules and write a scoped JSON report. Python 3.10+."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import stat
import sys
import tempfile
import time
import traceback
import unittest

SCHEMA = "easyeda-regression-report/v1"
IGNORED_DIRS = {"__pycache__", ".git", ".pytest_cache"}


class InvalidInput(ValueError):
    pass


def checked_path(value):
    """Check lexical ancestors before resolve hides symlinks or Windows junctions."""
    path = Path(os.path.abspath(os.fspath(value)))
    for part in reversed((path, *path.parents)):
        try:
            info = part.lstat()
        except FileNotFoundError:
            continue
        if (stat.S_ISLNK(info.st_mode)
                or getattr(info, "st_file_attributes", 0) & 0x400):
            raise InvalidInput(f"Symlink/reparse path is unsupported: {part}")
    if path.resolve(strict=False) != path:
        raise InvalidInput(f"Path alias is unsupported: {path}")
    return path


def guard_output(root, output):
    output = checked_path(output)
    if output == root or root in output.parents:
        raise InvalidInput("Report must be outside the skill directory")
    if output.exists():
        info = output.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_nlink > 1:
            raise InvalidInput("Report must be a regular file without hardlink aliases")
        try:
            prior = json.loads(output.read_text(encoding="utf-8"))
        except (ValueError, UnicodeError) as exc:
            raise InvalidInput("Refusing to overwrite an unrelated report file") from exc
        if not isinstance(prior, dict) or prior.get("schema") != SCHEMA:
            raise InvalidInput("Refusing to overwrite an unrelated report file")
    return output


def input_inventory(root):
    """Hash script/test inputs, excluding generated bytecode/cache directories."""
    rows = []
    for folder in (root / "scripts", root / "tests", root / "assets"):
        if not folder.is_dir():
            if folder.name == "assets" and not folder.exists():
                continue
            raise InvalidInput(f"Required directory is missing: {folder}")
        for directory, dirs, names in os.walk(folder, followlinks=False):
            dirs[:] = sorted(d for d in dirs if d not in IGNORED_DIRS)
            for name in dirs:
                checked_path(Path(directory) / name)
            for name in sorted(names):
                if name.endswith((".pyc", ".pyo")):
                    continue
                path = checked_path(Path(directory) / name)
                before = path.stat()
                if not stat.S_ISREG(before.st_mode):
                    raise InvalidInput(f"Nonregular test input: {path}")
                data = path.read_bytes()
                after = path.stat()
                signature = lambda s: (s.st_dev, s.st_ino, s.st_size, s.st_mtime_ns)
                if signature(before) != signature(after) or len(data) != before.st_size:
                    raise InvalidInput(f"Input changed while hashing: {path}")
                rows.append({"path": path.relative_to(root).as_posix(),
                             "size": len(data), "sha256": hashlib.sha256(data).hexdigest()})
    return sorted(rows, key=lambda row: row["path"])


class CountingResult(unittest.TextTestResult):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.successes = []

    def addSuccess(self, test):
        super().addSuccess(test)
        self.successes.append(test.id())


def discover(root, inputs):
    """Discover every test_*.py recursively, even in directories without __init__.py.

    Test files are independent unittest modules; load_tests is honored. Unique
    module names avoid collisions between equal basenames in different folders.
    """
    files = [row["path"] for row in inputs
             if row["path"].startswith("tests/")
             and Path(row["path"]).match("test_*.py")]
    suite, errors, skips, modules = unittest.TestSuite(), [], [], []
    for relative in files:
        path = root / relative
        name = "_pcb_regression_" + hashlib.sha256(relative.encode()).hexdigest()[:16]
        old_module = sys.modules.get(name)
        old_path = sys.path[:]
        try:
            sys.path[:0] = [str(path.parent), str(root / "tests"), str(root / "scripts")]
            spec = importlib.util.spec_from_file_location(name, path)
            if spec is None or spec.loader is None:
                raise ImportError(f"Cannot load {relative}")
            module = importlib.util.module_from_spec(spec)
            sys.modules[name] = module
            modules.append((name, old_module))
            spec.loader.exec_module(module)
            loader = unittest.TestLoader()
            loaded = loader.loadTestsFromModule(module)
            if loaded.countTestCases() == 0:
                errors.append({"path": relative, "reason": "Test module discovered zero tests"})
            errors.extend({"path": relative, "reason": reason} for reason in loader.errors)
            suite.addTests(loaded)
        except unittest.SkipTest as exc:
            skips.append({"test": relative, "reason": str(exc), "phase": "import"})
        except (Exception, SystemExit) as exc:
            errors.append({"path": relative,
                           "reason": f"{type(exc).__name__}: {exc}",
                           "traceback": traceback.format_exc()})
        finally:
            sys.path[:] = old_path
    return suite, files, errors, skips, modules


def write_report(root, output, report):
    output = guard_output(root, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    guard_output(root, output)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n",
                                         dir=output.parent, prefix=".regression-",
                                         suffix=".tmp", delete=False) as stream:
            temporary = Path(stream.name)
            json.dump(report, stream, ensure_ascii=False, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        guard_output(root, output)
        os.replace(temporary, output)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def run_regression(root, output, *, strict_skips=False, stream=None):
    root = checked_path(root)
    output = guard_output(root, output)  # Before importing or running any test code.
    started = time.monotonic()
    report = {
        "schema": SCHEMA, "scope": "Skill software regression only; no EDA, circuit or physical-board qualification.",
        "skillRoot": str(root), "python": sys.version,
        "startedAtUtc": datetime.now(timezone.utc).isoformat(),
        "strictSkips": bool(strict_skips), "status": "ERROR", "exitCode": 2,
        "testsRun": 0, "passed": 0, "failures": 0, "errors": 0, "skips": 0,
        "expectedFailures": 0, "unexpectedSuccesses": 0,
        "testFiles": [], "inputs": [], "inputsUnchanged": None,
        "discoveryErrors": [], "runnerErrors": [],
        "failureDetails": [], "errorDetails": [], "skipDetails": [],
        "expectedFailureDetails": [], "unexpectedSuccessDetails": [],
        "limitations": ["Only scripts/, tests/ and assets/ files are hashed; external libraries, metadata, references and EDA state are not certified.",
                        "Failure/error counts are unittest events; multiple failing subtests or class fixtures may not sum to testsRun.",
                        "Independent test modules are loaded recursively; package-relative imports are not supported."]}
    result, modules = None, []
    old_bytecode = sys.dont_write_bytecode
    old_path = sys.path[:]
    try:
        sys.dont_write_bytecode = True
        report["inputs"] = input_inventory(root)
        suite, files, errors, skips, modules = discover(root, report["inputs"])
        report["testFiles"], report["discoveryErrors"], report["skipDetails"] = files, errors, skips
        sys.path[:0] = [str(root / "tests"), str(root / "scripts")]
        runner = unittest.TextTestRunner(stream=stream or sys.stderr, verbosity=1,
                                         resultclass=CountingResult, buffer=True)
        # Keep a result even if a test interrupts the suite before runner.run returns.
        result = runner._makeResult()
        result.failfast = runner.failfast
        result.buffer = runner.buffer
        result.startTestRun()
        try:
            suite.run(result)
        finally:
            result.stopTestRun()
    except (Exception, SystemExit, KeyboardInterrupt) as exc:
        report["runnerErrors"].append({"reason": f"{type(exc).__name__}: {exc}",
                                       "traceback": traceback.format_exc()})
    finally:
        sys.dont_write_bytecode = old_bytecode
        sys.path[:] = old_path
        for name, old_module in reversed(modules):
            if old_module is None:
                sys.modules.pop(name, None)
            else:
                sys.modules[name] = old_module
    if result is not None:
        report.update(testsRun=result.testsRun, passed=len(result.successes),
                      failures=len(result.failures), errors=len(result.errors),
                      expectedFailures=len(result.expectedFailures),
                      unexpectedSuccesses=len(result.unexpectedSuccesses))
        for key, values in (("failureDetails", result.failures), ("errorDetails", result.errors),
                            ("expectedFailureDetails", result.expectedFailures)):
            report[key] = [{"test": test.id(), "traceback": detail} for test, detail in values]
        report["skipDetails"].extend({"test": test.id(), "reason": reason, "phase": "test"}
                                     for test, reason in result.skipped)
        report["unexpectedSuccessDetails"] = [test.id() for test in result.unexpectedSuccesses]
    report["skips"] = len(report["skipDetails"])
    try:
        after = input_inventory(root)
        report["inputsUnchanged"] = after == report["inputs"]
        if not report["inputsUnchanged"]:
            report["inputsAfter"] = after
            report["runnerErrors"].append({"reason": "Script/test inputs changed during the run"})
    except (ValueError, OSError) as exc:
        report["inputsUnchanged"] = False
        report["runnerErrors"].append({"reason": f"Cannot verify final inputs: {exc}"})
    if report["testsRun"] == 0:
        report["runnerErrors"].append({"reason": "Zero tests actually ran"})
    if report["discoveryErrors"] or report["runnerErrors"] or report["errors"]:
        status, code = "ERROR", 2
    elif report["failures"] or report["unexpectedSuccesses"]:
        status, code = "FAIL", 1
    elif report["skips"] or report["expectedFailures"]:
        status, code = "PARTIAL", 1 if strict_skips and report["skips"] else 0
    else:
        status, code = "PASS", 0
    report.update(status=status, exitCode=code, durationSeconds=round(time.monotonic() - started, 6))
    write_report(root, output, report)
    return report


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="JSON report outside the skill directory")
    parser.add_argument("--strict-skips", action="store_true", help="Return 1 for otherwise nonfailing runs with skips")
    args = parser.parse_args(argv)
    try:
        report = run_regression(Path(__file__).absolute().parents[1], args.out,
                                strict_skips=args.strict_skips)
    except (ValueError, OSError, UnicodeError) as exc:
        print(f"Regression input/output error: {exc}", file=sys.stderr)
        return 2
    print(json.dumps({key: report[key] for key in
                      ("status", "exitCode", "testsRun", "passed", "failures", "errors", "skips")},
                     ensure_ascii=False))
    return report["exitCode"]


if __name__ == "__main__":
    sys.exit(main())
